name: Build host-client

on:
  pull_request:
    branches: [main]
    paths:
      - "host-client/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./host-client

jobs:
  Build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -DskipTests=true clean install

  Test:
    needs: [Build]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Test with Maven
        run: mvn test

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          flags: host-client
